### ISSUE TITLE
Así no se recorre un iterable

### ISSUE THREAD

**Issue by lmagarin** [rnicar245/Formulario-Completo#14]
https://github.com/rnicar245/Formulario-Completo/blob/0f727c2f019c7a5bc1883b4387f0569d92d31bf5/index.js#L15
https://stackoverflow.com/a/22754453

**Comment by rnicar245** [comment]
Lo recorro de esa forma porque no quería recoger el último valor cuyo índice no es numérico, a diferencia del resto, así que me aproveché del for in que coge los índices para controlarlo.
