### ISSUE TITLE
¿Para qué true/false?

### ISSUE THREAD

**Issue by lmagarin** [rnicar245/Formulario-Completo#5]
https://github.com/rnicar245/Formulario-Completo/blob/0aae55619a6a7134a6da9d9997e89a2f86a42a38/index.js#L65

**Comment by rnicar245** [comment]
Pongo los return para que luego en el every de validar el formulario entero funcione.

**Comment by lmagarin** [comment]
Pero no lo necesitabas. Procura analizar antes de codificar. Conoces muchas técnicas que solucionan el problema. Las banderas se pueden quedar obsoletas
